services:
  elasticsearch:
    image: elasticsearch:9.2.1
    container_name: es-projet
    mem_limit: 512m
    memswap_limit: 512m
    environment:
      # Désactive l'authentification et HTTPS pour ce TP
      - xpack.security.enabled=false
      # Si sécurité activée, fournir un mot de passe pour l'utilisateur "elastic"
      #- "ELASTIC_PASSWORD=ISEN"
      # Requis pour un cluster à un seul noeud
      - discovery.type=single-node
      # Allocation mémoire (IMPORTANT: ajustez selon votre machine)
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      # Allow CORS
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE
    ports:
      - "9200:9200"
    volumes:
      # Volume pour persister les données d'Elasticsearch
      - esdata-projet:/usr/share/elasticsearch/data
    healthcheck:
      # Attend que l'API soit prête (status yellow ou green)
      test: ["CMD-SHELL", "curl -s 'http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s' | grep -q '\"status\":\"\\(yellow\\|green\\)\"'"]
      #test: ["CMD-SHELL", "curl -s 'http://elastic:ISEN@localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s' | grep -q '\"status\":\"\\(yellow\\|green\\)\"'"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  flask:
    build: .
    container_name: flask-app
    ports:
      - "80:5000"
    volumes:
      - ./www:/app/www:ro
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: always

volumes:
  esdata-projet:
    driver: local